version: "3.9"
services:
  httpd:
    container_name: app-web
    build:
      context: ./docker
      dockerfile: web.dockerfile
    ports:
      - 8080:80
    environment:
      XDEBUG_CONFIG: client_host=${DOCKER_HOST_IP:-} client_port=9010
    volumes:
      - ./application:/app

  mysql:
    container_name: app-mysql
    image: mysql:8.0.30
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_ALLOW_EMPTY_PASSWORD: 'True'
    volumes:
        - app_mysql:/var/lib/mysql
        - ./docker/confs/mysql/my.cnf:/etc/mysql/conf.d/mycustom.cnf

  pma:
    container_name: app-pma
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  redis:
    container_name: app-redis
    image: redis:7.0.11-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - app_redis:/data

  mhog:
    container_name: app-mailhog
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  app_mysql:
  app_redis:
