services:
  httpd:
    container_name: raft-web
    build:
      context: ./docker
      dockerfile: web.dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    ports:
      - 8080:80
    environment:
      XDEBUG_CONFIG: '${RAFT_XDEBUG_CONFIG:-client_host=host.docker.internal} client_port=9010'
    volumes:
      - ./application:/app
    depends_on:
      - mysql
      - redis
      - mpit
      - pma

  mysql:
    container_name: raft-mysql
    image: mysql:8.1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=application
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
    volumes:
      - app_mysql:/var/lib/mysql

  pma:
    container_name: raft-pma
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - MEMORY_LIMIT=2048
      - UPLOAD_LIMIT=512M

  redis:
    container_name: raft-redis
    image: redis:7.2.0-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - app_redis:/data

  mpit:
    container_name: raft-mailpit
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      - TZ=America/Sao_Paulo
networks:
  raft:
    driver: bridge

volumes:
  app_mysql:
  app_redis:
